strava_authorization_link: 'https://www.strava.com/oauth/authorize?client_id=39626&response_type=code&redirect_uri=https://chaykhoe55555.herokuapp.com&approval_prompt=force&scope=read,activity:read'
strava_client_id: '39626'
strava_client_secret: 'a182b14ee7f10e47aceadcbe1b552e54f3797103'
